version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"
  miner1:
    build: .
    depends_on:
      - api
  miner2:
    build: .
    depends_on:
      - api
networks:
  default:
    driver: bridge