version: '3.8'
services:
  miner1:
    build:
      context: ../
      dockerfile: docker/miner/Dockerfile
    image: blockchain-miner
    environment:
      - MINERNODE_CURRENT_ADDRESS=http://miner1:5000
      - MINERNODE_PEERS=http://full-node1:5000,http://full-node2:5000,http://full-node3:5000
    ports:
      - "5001:5000"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
    depends_on:
      - full-node1
      - full-node2
      - full-node3

  miner2:
    build:
      context: ../
      dockerfile: docker/miner/Dockerfile
    image: blockchain-miner
    environment:
      - MINERNODE_CURRENT_ADDRESS=http://miner2:5000
      - MINERNODE_PEERS=http://full-node1:5000,http://full-node2:5000,http://full-node3:5000
    ports:
      - "5002:5000"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
    depends_on:
      - full-node1
      - full-node2
      - full-node3

  miner3:
    build:
      context: ../
      dockerfile: docker/miner/Dockerfile
    image: blockchain-miner
    environment:
      - MINERNODE_CURRENT_ADDRESS=http://miner3:5000
      - MINERNODE_PEERS=http://full-node1:5000,http://full-node2:5000,http://full-node3:5000
    ports:
      - "5003:5000"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
    depends_on:
      - full-node1
      - full-node2
      - full-node3

  full-node1:
    build:
      context: ../
      dockerfile: docker/full-node/Dockerfile
    image: blockchain-full-node
    environment:
      - FULLNODE_CURRENT_ADDRESS=http://full-node1:5000
      - FULLNODE_PEERS=http://full-node2:5000,http://full-node3:5000
    ports:
      - "5001:5000"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G

  full-node2:
    build:
      context: ../
      dockerfile: docker/full-node/Dockerfile
    image: blockchain-full-node
    environment:
      - FULLNODE_CURRENT_ADDRESS=http://full-node2:5000
      - FULLNODE_PEERS=http://full-node1:5000,http://full-node3:5000
    ports:
      - "5002:5000"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G

  full-node3:
    build:
      context: ../
      dockerfile: docker/full-node/Dockerfile
    image: blockchain-full-node
    environment:
      - FULLNODE_CURRENT_ADDRESS=http://full-node3:5000
      - FULLNODE_PEERS=http://full-node1:5000,http://full-node2:5000
    ports:
      - "5003:5000"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G

  user-api:
    build:
      context: ../
      dockerfile: docker/user-api/Dockerfile
    image: blockchain-user-api
    environment:
      - USERAPI_CURRENT_ADDRESS=http://user-api:5000
      - USERAPI_PEERS=http://full-node1:5000,http://full-node2:5000,http://full-node3:5000
    ports:
      - "8080:8080"
    depends_on:
      - full-node1
      - full-node2
      - full-node3