version: '3.8'
services:
  miner1:
    build:
      context: ../
      dockerfile: docker/miner/Dockerfile
    image: blockchain-miner
    ports:
      - "5001:5000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  miner2:
    build:
      context: ../
      dockerfile: docker/miner/dockerfile
    image: blockchain-miner
    ports:
      - "5002:5000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  miner3:
    build:
      context: ../
      dockerfile: docker/miner/dockerfile
    image: blockchain-miner
    ports:
      - "5003:5000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G