version: '3.8'
services:
  miner-node1:
    build:
      context: ../
      dockerfile: docker/miner-node/Dockerfile
    image: blockchain-miner-node
    environment:
      - NODE_ADDRESS=http://miner-node1:5000
      - NODE_INITIAL_PEERS=${NODE_INITIAL_PEERS}
      - NODE_INITIAL_BLOCK_DIFFICULTY=${NODE_INITIAL_BLOCK_DIFFICULTY}
    ports:
      - "5011:5000"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
    depends_on:
      - full-node1
      - full-node2
      - full-node3

  miner-node2:
    build:
      context: ../
      dockerfile: docker/miner-node/Dockerfile
    image: blockchain-miner-node
    environment:
      - NODE_ADDRESS=http://miner-node2:5000
      - NODE_INITIAL_PEERS=${NODE_INITIAL_PEERS}
      - NODE_INITIAL_BLOCK_DIFFICULTY=${NODE_INITIAL_BLOCK_DIFFICULTY}
    ports:
      - "5012:5000"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
    depends_on:
      - full-node1
      - full-node2
      - full-node3

  miner-node3:
    build:
      context: ../
      dockerfile: docker/miner-node/Dockerfile
    image: blockchain-miner-node
    environment:
      - NODE_ADDRESS=http://miner-node3:5000
      - NODE_INITIAL_PEERS=${NODE_INITIAL_PEERS}
      - NODE_INITIAL_BLOCK_DIFFICULTY=${NODE_INITIAL_BLOCK_DIFFICULTY}
    ports:
      - "5013:5000"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
    depends_on:
      - full-node1
      - full-node2
      - full-node3

  full-node1:
    build:
      context: ../
      dockerfile: docker/full-node/Dockerfile
    image: blockchain-full-node
    environment:
      - NODE_ADDRESS=http://full-node1:5000
      - NODE_INITIAL_PEERS=${NODE_INITIAL_PEERS}
      - NODE_INITIAL_BLOCK_DIFFICULTY=${NODE_INITIAL_BLOCK_DIFFICULTY}
    ports:
      - "5001:5000"

  full-node2:
    build:
      context: ../
      dockerfile: docker/full-node/Dockerfile
    image: blockchain-full-node
    environment:
      - NODE_ADDRESS=http://full-node2:5000
      - NODE_INITIAL_PEERS=${NODE_INITIAL_PEERS}
      - NODE_INITIAL_BLOCK_DIFFICULTY=${NODE_INITIAL_BLOCK_DIFFICULTY}
    ports:
      - "5002:5000"

  full-node3:
    build:
      context: ../
      dockerfile: docker/full-node/Dockerfile
    image: blockchain-full-node
    environment:
      - NODE_ADDRESS=http://full-node3:5000
      - NODE_INITIAL_PEERS=${NODE_INITIAL_PEERS}
      - NODE_INITIAL_BLOCK_DIFFICULTY=${NODE_INITIAL_BLOCK_DIFFICULTY}
    ports:
      - "5003:5000"

  user-api-node:
    build:
      context: ../
      dockerfile: docker/user-api-node/Dockerfile
    image: blockchain-user-api-node
    environment:
      - NODE_ADDRESS=http://user-api-node:8080
      - NODE_INITIAL_PEERS=${NODE_INITIAL_PEERS}
      - NODE_INITIAL_BLOCK_DIFFICULTY=${NODE_INITIAL_BLOCK_DIFFICULTY}
    ports:
      - "8080:8080"
    depends_on:
      - full-node1
      - full-node2
      - full-node3